### ISSUE TITLE
[FR] option to submenu only

### ISSUE THREAD

**Issue by mrx23dot** [bhch/dictionary-plus#11]
Modifying every double click is kinda annoying, an option would be nice to only do look up via the current extended menu.

**Comment by bhch** [comment]
Hi, thank you for your suggestion. I'll include this in the next release (possibly by this weekend).

**Comment by bhch** [comment]
I've shipped this feature in the latest v5.6.

You can disable triggering the popup on double click in the settings menu:

![dict-plus-popup-settings](https://user-images.githubusercontent.com/6051897/218260174-1169db56-6b78-41fe-8353-f90efed5672e.png)

Update your extension to get this feature. Again, thank you opening this issue.

**Comment by bhch** [comment]
That's a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=85686) in Firefox. It doesn't return selections from inputs/textareas.

However, I'll look for some workarounds.

I've just created Issue #12 to track this.
