### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by mrx23dot** [bhch/dictionary-plus#17]
e.g. proliferated 
![image](https://github.com/bhch/dictionary-plus/assets/4163396/f16839a6-7946-440d-b5da-5e595a8b05bb)

![image](https://github.com/bhch/dictionary-plus/assets/4163396/5ad1aaf7-e361-4661-8c6c-bed0b40cc7dd)

**Comment by bhch** [comment]
Thanks for reporting this.

I've fixed the issue and released a new version. Please update and test it out.
