### ISSUE TITLE
STOP WORKING! UNABLE TO DEFINE ANY WORD SINCE RECENT UPDATE: JAN 10, 2022.

### ISSUE THREAD

**Issue by Luckybritbrit15** [bhch/dictionary-plus#4]
I truly enjoyed using dictionary plus and I was having a great experience until January 10, 2022 update. The adds-on took long to search for a definition when double-clicked on a word, in which after did not find any definition. This occurred with every word I double-clicked, from the simplest words such as tube, pregnancy, and normal etc. I was enjoying the adds-on very much, as a result, I had to make a account with Github just so I can be able to report this issue, in order for it to be resolved

**Comment by bhch** [comment]
Hi, I appreciate your effort to report this issue. Thank you.

For future, I'll setup an easier way to send feedback and report bugs.

Please answer the following question:

 1. Your Firefox version
 2. Your Country
 3. Your browser's main language
 4. Can you open https://www.google.com or it blocked in your country or by your internet provider?

**Comment by Luckybritbrit15** [comment]
Ok, please do make a easier way to communicate. 

1. Firefox version is 95.0,2 (64-bit)
2. Jamaica
3. English
4. Yes I can open the link above.

**Comment by bhch** [comment]
Hi, I did some tests using Firefox 95.0.2 (and also the newest 96.0), but everything is working fine for me.

I've no idea how it's not working for you.

Anyway, I'll soon release a new version which will give me error reports so I can know exactly what went wrong.

Thank you.

**Comment by bhch** [comment]
@Luckybritbrit15 I've just released a new version (5.3). It will now display a detailed error message when something goes wrong.

Please update the extension. And if there's still an error, please paste the error message here.

Thank you.

**Comment by Luckybritbrit15** [comment]
Ok, Thanks much. I will go ahead and update it, as well as  Firefox. I
really appreciate the assistance. I was seeing a improvement recently where
I am about to define few words. It appears it is slowly working back for
me, I hope the update will resolve the issue. Thanks again for your help
and immediate response 👍.

**Comment by Luckybritbrit15** [comment]
#
![ERROR 2](https://user-images.githubusercontent.com/97490815/149593387-f6f87ba2-85c7-4998-a150-7172b356e0c7.png)
![Error](https://user-images.githubusercontent.com/97490815/149593413-d89f0e8a-dbeb-4685-b5cd-80b6a52f8a0b.png)

**Comment by bhch** [comment]
It's really strange that it's not working for you.

I've created a debug mode extension for you. 

1. Download debug mode extension from here: [dictionary-plus-debug-mode.zip](https://github.com/bhch/dictionary-plus/files/7874364/dictionary-plus-debug-mode.zip).
2. Remove Dictionary Plus add-on from your Firefox.
3. Then install the package you downloaded above. Follow instructions on this page: https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/
4. Then open a new page and try to double-click on some words.
5. Copy the error message and paste it here.

**Comment by Luckybritbrit15** [comment]
```
)]}'
1b;["2j7jYZ3QCcTCytMP87GfgAo"]3;[1]2;[]
```

**Comment by Luckybritbrit15** [comment]
```
)]}'
1b;["JD_jYcexAr2lytMPwteduA8"]3;[1]2;[]
```

**Comment by Luckybritbrit15** [comment]
Error Messages:

1.  Defining welcome:

```
)]}'
1b;["aUDjYfvHM6OkytMP9t-NsAc"]3;[1]2;[]
```


2. Defining Nurses:

```
)]}'
1b;["nUDjYc6YLJC1ytMP-IyI8AI"]3;[1]2;[]
```


3. Defining Education:

```
)]}'
1b;["vEDjYcnUAoHDytMP-b2UoA4"]3;[1]2;[]
```

4. Defining school

```
)]}'
1b;["0UDjYYCoNLvAytMPy-GmuAo"]3;[1]2;[]
```


These are some of the error messages received when attempted to define the
following words above them.

**Comment by bhch** [comment]
Are you using a VPN? Or maybe you are using an American internet service provider?

**Comment by bhch** [comment]
Hi, I've just released a new version - 5.4. Hopefully it will resolve your issue. Please install and see if it works.

**Comment by silverwings15** [comment]
i don't have an American IP but the update fixed the issue for me as well 🎉

**Comment by bhch** [comment]
That's great!

Thank you for reporting this issue and for your patience through this.

**Comment by Luckybritbrit15** [comment]
Thank you, Hun😃
It is working now🤗. I appreciated this alot😇.
You're Welcome🙌
